config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
  positions:
    filename: /run/promtail/positions.yaml
  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: ["__meta_kubernetes_pod_label_app"]
          action: replace
          target_label: "app"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 128Mi

